// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230620115432_CreateProductsTable")]
    partial class CreateProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeatureApp.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f5b5b7c-92cb-4d29-aaf9-afc01df898ce"),
                            CreatedBy = new Guid("e56d0288-9e4f-49ca-9c23-fcaa9c9dfd02"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(223),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Grunge Skater Jeans",
                            Price = 68m,
                            Sku = "AWMGSJ"
                        },
                        new
                        {
                            Id = new Guid("17097e37-b580-4d9d-9710-829fce6cd3bb"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Polo Shirt",
                            Price = 35m,
                            Sku = "AWMPS"
                        },
                        new
                        {
                            Id = new Guid("32a4ea55-39f1-4eca-a4f0-86b0c37280f4"),
                            CreatedBy = new Guid("301a39c9-1716-47da-9df2-1ffd6540ead2"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(292),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Skater Graphic T-Shirt",
                            Price = 33m,
                            Sku = "AWMSGT"
                        },
                        new
                        {
                            Id = new Guid("801a34ea-499a-4e3b-90cc-aeac28e142ba"),
                            CreatedBy = new Guid("4b342a2c-cf76-4040-afba-086c1dffb071"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(298),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Slicker Jacket",
                            Price = 125m,
                            Sku = "AWMSJ"
                        },
                        new
                        {
                            Id = new Guid("4629fa34-4adb-41c1-9b28-13f1c8401a1c"),
                            CreatedBy = new Guid("d732f60f-9909-4db1-a709-3e5f6dddae36"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(303),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Thermal Fleece Jacket",
                            Price = 60m,
                            Sku = "AWMTFJ"
                        },
                        new
                        {
                            Id = new Guid("c05e6026-cc88-4518-bafa-50b63cdb30b0"),
                            CreatedBy = new Guid("e6db081c-141a-47b7-8cc8-86af7e56270d"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(307),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Unisex Thermal Vest",
                            Price = 95m,
                            Sku = "AWMUTV"
                        },
                        new
                        {
                            Id = new Guid("0aaa9b00-00c6-4ba5-baa2-05a7215808cb"),
                            CreatedBy = new Guid("901effc6-1fa9-48ae-be6b-bd643d7e72a8"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(356),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "V-Neck Pullover",
                            Price = 65m,
                            Sku = "AWMVNP"
                        },
                        new
                        {
                            Id = new Guid("a2cd87b8-fcaa-469c-a929-6e71aeeff7ea"),
                            CreatedBy = new Guid("338ff618-61d4-4bda-ac42-2630ed407bc0"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(364),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "V-Neck Sweater",
                            Price = 65m,
                            Sku = "AWMVNS"
                        },
                        new
                        {
                            Id = new Guid("753b3150-d6f3-412f-985f-ef0de6428168"),
                            CreatedBy = new Guid("392b751c-0f29-4159-ac97-9215a3cbcff3"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(406),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "V-Neck T-Shirt",
                            Price = 17m,
                            Sku = "AWMVNT"
                        },
                        new
                        {
                            Id = new Guid("d944e3f6-e427-445d-ac5e-d8762457ee66"),
                            CreatedBy = new Guid("7c13d4fb-c44a-416d-bfed-ba06eb87f1c8"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(410),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Bamboo Thermal Ski Coat",
                            Price = 99m,
                            Sku = "AWWBTSC"
                        },
                        new
                        {
                            Id = new Guid("14c25491-d1d0-4c5b-8626-9b11b1bef8b7"),
                            CreatedBy = new Guid("e6c150fe-de66-4814-adf3-d3223f46c339"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(420),
                            Description = "",
                            IsAvailable = false,
                            IsNew = false,
                            Name = "Cross-Back Training Tank",
                            Price = 0m,
                            Sku = "AWWCTT"
                        },
                        new
                        {
                            Id = new Guid("8531f7be-520c-41f3-93fe-2fb3f53b6e08"),
                            CreatedBy = new Guid("4f95fdf7-fdfc-4205-9819-bfc54c4e70c2"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(425),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Grunge Skater Jeans",
                            Price = 68m,
                            Sku = "AWWGSJ"
                        },
                        new
                        {
                            Id = new Guid("37ab027e-579f-4d03-b906-3b173aaf2bbf"),
                            CreatedBy = new Guid("1e1013ee-a58e-47f6-9dd0-7bdadc9d1beb"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(430),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Slicker Jacket",
                            Price = 125m,
                            Sku = "AWWSJ"
                        },
                        new
                        {
                            Id = new Guid("33cb5ac5-e188-46a6-a36b-9edba3840e1f"),
                            CreatedBy = new Guid("2405c6dd-7518-4df7-9cca-821aceb6dd66"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(435),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Stretchy Dance Pants",
                            Price = 55m,
                            Sku = "AWWSDP"
                        },
                        new
                        {
                            Id = new Guid("6885910e-654d-4304-a686-0996960e07f2"),
                            CreatedBy = new Guid("1ec3139e-6eb4-4411-b5a4-b7e8dc0d2e9d"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(446),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Ultra-Soft Tank Top",
                            Price = 22m,
                            Sku = "AWWUTT"
                        },
                        new
                        {
                            Id = new Guid("0001bf54-dad7-4485-820a-3e659b5f1532"),
                            CreatedBy = new Guid("11ae6566-0cdf-4275-9bfa-8bf638f8c8c2"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(455),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Unisex Thermal Vest",
                            Price = 95m,
                            Sku = "AWWUTV"
                        },
                        new
                        {
                            Id = new Guid("06b9d422-12c2-48a6-b69a-df5459dab549"),
                            CreatedBy = new Guid("7e22a0c8-075e-43e0-a523-f80afdcba511"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(460),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "V-Next T-Shirt",
                            Price = 17m,
                            Sku = "AWWVNT"
                        },
                        new
                        {
                            Id = new Guid("47103682-53d9-44af-858d-1334fc158f3e"),
                            CreatedBy = new Guid("84290e11-97f7-4783-93b1-2d3a83b78db5"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(466),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Blueberry Mineral Water",
                            Price = 2.8m,
                            Sku = "MWB"
                        },
                        new
                        {
                            Id = new Guid("d1b779b3-ff06-4064-8994-ad573ac56117"),
                            CreatedBy = new Guid("beb90bae-b46c-4a14-bc20-9ec1599fc162"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(474),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Lemon-Lime Mineral Water",
                            Price = 2.8m,
                            Sku = "MWLL"
                        },
                        new
                        {
                            Id = new Guid("03b10d77-c7d8-4c56-8e7e-0d9370f51b2b"),
                            CreatedBy = new Guid("0812c0c3-ca82-4b97-89dd-7b5bffab2362"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(479),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Orange Mineral Water",
                            Price = 2.8m,
                            Sku = "MWO"
                        },
                        new
                        {
                            Id = new Guid("fe6fc5b7-b808-4c04-ab60-ca9a7aa0db57"),
                            CreatedBy = new Guid("e66f737d-38aa-4648-8f73-d27b9dac63c4"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(483),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Peach Mineral Water",
                            Price = 2.8m,
                            Sku = "MWP"
                        },
                        new
                        {
                            Id = new Guid("662c166f-a7bf-4295-b381-efd2b6898ea4"),
                            CreatedBy = new Guid("24ca322f-3233-4bb8-9046-ba7cc3681039"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(487),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Raspberry Mineral Water",
                            Price = 2.8m,
                            Sku = "MWR"
                        },
                        new
                        {
                            Id = new Guid("1c50ceb2-17ef-4d00-88de-9d710bf089a8"),
                            CreatedBy = new Guid("36a126ac-7f08-43dd-ad44-a7c5a65f0848"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(494),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Strawberry Mineral Water",
                            Price = 2.8m,
                            Sku = "MWS"
                        },
                        new
                        {
                            Id = new Guid("c34f03e2-f73a-41f0-ba2b-1015eea686e0"),
                            CreatedBy = new Guid("a6a54f09-749f-4336-af42-97e03772573f"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(502),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "In the Kitchen with H+ Sport",
                            Price = 24.99m,
                            Sku = "PITK"
                        },
                        new
                        {
                            Id = new Guid("5bf19323-ea5f-4582-84a6-f60cdbaaec7a"),
                            CreatedBy = new Guid("382a9873-3a2d-4668-bd84-8855c73dfdcd"),
                            CreatedDate = new DateTime(2023, 6, 20, 16, 54, 31, 795, DateTimeKind.Local).AddTicks(510),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Calcium 400 IU (150 tablets)",
                            Price = 9.99m,
                            Sku = "SC400"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
