// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230525133823_updatedatabase")]
    partial class updatedatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeatureApp.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae61e959-d1de-4712-8cd2-a0f4a27156a4"),
                            CreatedBy = new Guid("1bf164a7-6e21-45dc-8650-13d8bf076c3e"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8849),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Grunge Skater Jeans",
                            Price = 68m,
                            Sku = "AWMGSJ"
                        },
                        new
                        {
                            Id = new Guid("aa6ebdd6-b9b9-4fe5-8211-48c1ce45b57c"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Polo Shirt",
                            Price = 35m,
                            Sku = "AWMPS"
                        },
                        new
                        {
                            Id = new Guid("98ba6056-8467-47ee-9b6d-4e5f4843d191"),
                            CreatedBy = new Guid("30fc29b5-aff8-474b-a2b1-a9e2592844aa"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8876),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Skater Graphic T-Shirt",
                            Price = 33m,
                            Sku = "AWMSGT"
                        },
                        new
                        {
                            Id = new Guid("7b38a6c6-01d6-47b8-9c70-21b007a6aa27"),
                            CreatedBy = new Guid("fbd44789-d213-4482-a89e-4f20499ac88b"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8881),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Slicker Jacket",
                            Price = 125m,
                            Sku = "AWMSJ"
                        },
                        new
                        {
                            Id = new Guid("2d6922c8-d514-42b8-908c-fab3dc7db594"),
                            CreatedBy = new Guid("6aad02a9-8b12-4639-aa6e-91fce2715199"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8902),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Thermal Fleece Jacket",
                            Price = 60m,
                            Sku = "AWMTFJ"
                        },
                        new
                        {
                            Id = new Guid("93d6a877-2e2d-4928-a192-5ada937f7e52"),
                            CreatedBy = new Guid("0613730e-c5f6-482b-994b-56c4589ef30a"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8906),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Unisex Thermal Vest",
                            Price = 95m,
                            Sku = "AWMUTV"
                        },
                        new
                        {
                            Id = new Guid("ba65699e-328f-4159-a193-e2fc49c7ff07"),
                            CreatedBy = new Guid("99b73bdb-e838-404b-a263-cd23e5325ff1"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8911),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "V-Neck Pullover",
                            Price = 65m,
                            Sku = "AWMVNP"
                        },
                        new
                        {
                            Id = new Guid("08edee98-66d5-4069-923b-902320bd23dd"),
                            CreatedBy = new Guid("4b09b6c3-e101-46a6-9b4f-3eb292aad80b"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8916),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "V-Neck Sweater",
                            Price = 65m,
                            Sku = "AWMVNS"
                        },
                        new
                        {
                            Id = new Guid("b3d7c044-5ffd-40f0-a95f-44c727dea350"),
                            CreatedBy = new Guid("f7708a18-96cc-409b-a399-54f845ab9d0c"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8926),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "V-Neck T-Shirt",
                            Price = 17m,
                            Sku = "AWMVNT"
                        },
                        new
                        {
                            Id = new Guid("a807c153-ab09-4ae3-a656-ef1efc339be7"),
                            CreatedBy = new Guid("8df2d7a1-53a3-4579-b4ba-6fcd9f6759eb"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8932),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Bamboo Thermal Ski Coat",
                            Price = 99m,
                            Sku = "AWWBTSC"
                        },
                        new
                        {
                            Id = new Guid("39faf3ba-bc1c-446c-9cfa-b5a9eba3369d"),
                            CreatedBy = new Guid("2bae3a44-35b0-4b97-b69f-821280596c1d"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8937),
                            Description = "",
                            IsAvailable = false,
                            IsNew = false,
                            Name = "Cross-Back Training Tank",
                            Price = 0m,
                            Sku = "AWWCTT"
                        },
                        new
                        {
                            Id = new Guid("5d462dc6-0d12-4b92-ae04-7e40bd611763"),
                            CreatedBy = new Guid("e2449132-01d8-440b-956b-84d2b1ad3b99"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8942),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Grunge Skater Jeans",
                            Price = 68m,
                            Sku = "AWWGSJ"
                        },
                        new
                        {
                            Id = new Guid("44332d9c-b567-43ca-b64d-2376ffbe7bf6"),
                            CreatedBy = new Guid("7582a606-22e4-4e6f-a97e-433a880a1cf8"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8953),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Slicker Jacket",
                            Price = 125m,
                            Sku = "AWWSJ"
                        },
                        new
                        {
                            Id = new Guid("f505f2cf-1dae-4b9c-ace8-fbed77f4cf34"),
                            CreatedBy = new Guid("c1934d0f-0d1c-43df-b74d-71f22f050c13"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8959),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Stretchy Dance Pants",
                            Price = 55m,
                            Sku = "AWWSDP"
                        },
                        new
                        {
                            Id = new Guid("ae876fa9-e83a-4242-b9de-f46fdd10748d"),
                            CreatedBy = new Guid("62e5da14-d316-4bd6-a26b-80864cf5c761"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8964),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Ultra-Soft Tank Top",
                            Price = 22m,
                            Sku = "AWWUTT"
                        },
                        new
                        {
                            Id = new Guid("e7a41e4c-df22-4209-aebf-e71f408873f5"),
                            CreatedBy = new Guid("181c6169-298c-4410-be16-be22877daf8f"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(8969),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Unisex Thermal Vest",
                            Price = 95m,
                            Sku = "AWWUTV"
                        },
                        new
                        {
                            Id = new Guid("adb78f6e-afdf-45ca-968a-a03ae4a8877e"),
                            CreatedBy = new Guid("4792910e-6ffa-4f56-8c54-724e78e092c7"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(9146),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "V-Next T-Shirt",
                            Price = 17m,
                            Sku = "AWWVNT"
                        },
                        new
                        {
                            Id = new Guid("c8698c08-2514-48eb-9b23-1b2e32120a81"),
                            CreatedBy = new Guid("977d9979-57ce-4180-bd91-4cb910fcebb6"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(9153),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Blueberry Mineral Water",
                            Price = 2.8m,
                            Sku = "MWB"
                        },
                        new
                        {
                            Id = new Guid("dc64c838-d59e-4983-91c2-17fa0a5334db"),
                            CreatedBy = new Guid("97b47faa-a1cf-4222-b46a-12b8e954adf0"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(9157),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Lemon-Lime Mineral Water",
                            Price = 2.8m,
                            Sku = "MWLL"
                        },
                        new
                        {
                            Id = new Guid("4e18bdbd-e25d-4d3e-9bd9-8c381503f97c"),
                            CreatedBy = new Guid("ca5f9830-61ca-4334-a84f-547ea7519104"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(9160),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Orange Mineral Water",
                            Price = 2.8m,
                            Sku = "MWO"
                        },
                        new
                        {
                            Id = new Guid("5539c177-9621-471d-86e0-54d488299c58"),
                            CreatedBy = new Guid("10c49d9f-898f-42ee-89c1-7ddb8b300b10"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(9166),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Peach Mineral Water",
                            Price = 2.8m,
                            Sku = "MWP"
                        },
                        new
                        {
                            Id = new Guid("a3cdb4af-bae4-4888-b7ef-d39f661089b0"),
                            CreatedBy = new Guid("116a1a2e-cd1b-43c4-a5ad-ab575fea16b7"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(9170),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Raspberry Mineral Water",
                            Price = 2.8m,
                            Sku = "MWR"
                        },
                        new
                        {
                            Id = new Guid("fdeb992a-6465-472a-b2e6-b2cc0e3258d7"),
                            CreatedBy = new Guid("d8f8fc88-c132-418b-875c-8c4b6f449c5b"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(9173),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Strawberry Mineral Water",
                            Price = 2.8m,
                            Sku = "MWS"
                        },
                        new
                        {
                            Id = new Guid("d58e4a7e-2d66-4129-b419-ffd6c8c85d7e"),
                            CreatedBy = new Guid("2bdacefb-eef3-4d8d-b84d-52988480adba"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(9176),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "In the Kitchen with H+ Sport",
                            Price = 24.99m,
                            Sku = "PITK"
                        },
                        new
                        {
                            Id = new Guid("99fc1098-87e5-427b-811b-81b503410ec6"),
                            CreatedBy = new Guid("6ab4137d-b362-4b88-aa18-a1cd352bec45"),
                            CreatedDate = new DateTime(2023, 5, 25, 18, 38, 23, 48, DateTimeKind.Local).AddTicks(9182),
                            Description = "",
                            IsAvailable = true,
                            IsNew = false,
                            Name = "Calcium 400 IU (150 tablets)",
                            Price = 9.99m,
                            Sku = "SC400"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
